# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Splunk.ACS
PackageVersion: 2.20.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: uninstallPrevious
Commands:
- acs
ReleaseDate: 2025-07-14
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/splunk/acs-cli/releases/download/v2.20.0/acs_v2.20.0_windows_amd64_installer.exe
  InstallerSha256: 8b78ac2c31e5ea176f6a3e67d3aa0c56c008969f7846b08ae1463106f09f0258
ManifestType: installer
ManifestVersion: 1.6.0