# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Splunk.ACS
PackageVersion: 2.25.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: uninstallPrevious
Commands:
- acs
ReleaseDate: 2026-07-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/splunk/acs-cli/releases/download/v2.25.0/acs_v2.25.0_windows_amd64_installer.exe
  InstallerSha256: 6a16a275fa906e9a03db82510f0a70e85bbf23117123b4b8ef426bac4401c1c2
ManifestType: installer
ManifestVersion: 1.6.0