# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Splunk.ACS
PackageVersion: 2.11.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: uninstallPrevious
Commands:
- acs
ReleaseDate: 2023-05-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/splunk/acs-cli/releases/download/v2.11.0/acs_v2.11.0_windows_amd64_installer.exe
  InstallerSha256: e947250be21708326e838aebe92497e54507778848e6f8959faf23533f22f6be
ManifestType: installer
ManifestVersion: 1.1.0